import { Component } from '@angular/core';
import { StockApiService } from '../../services/stock-api.service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { RupeePipe } from '../../core/pipes/rupee.pipe';

@Component({
  selector: 'app-stock-screener',
  standalone: true,
  imports: [CommonModule,FormsModule,RupeePipe,RouterModule],
  templateUrl: './stock-screener.component.html',
  styleUrl: './stock-screener.component.scss',
})
export class StockScreenerComponent {
  stockData: any[] = [
    {
        "symbol": "RELIANCE.BO",
        "companyName": "Reliance Industries Limited",
        "marketCap": 17247686007150,
        "sector": "Energy",
        "industry": "Oil & Gas Refining & Marketing",
        "beta": 0.566,
        "price": 1274.55,
        "lastAnnualDividend": 5,
        "volume": 392500,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "HDFCBANK.BO",
        "companyName": "HDFC Bank Limited",
        "marketCap": 14589310739233,
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "beta": 0.671,
        "price": 1906.55,
        "lastAnnualDividend": 19.5,
        "volume": 408716,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TCS.BO",
        "companyName": "Tata Consultancy Services Limited",
        "marketCap": 11935889428230,
        "sector": "Technology",
        "industry": "Information Technology Services",
        "beta": 0.451,
        "price": 3298.95,
        "lastAnnualDividend": 124,
        "volume": 70459,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "BHARTIARTL.BO",
        "companyName": "Bharti Airtel Limited",
        "marketCap": 10763844128046,
        "sector": "Communication Services",
        "industry": "Telecommunications Services",
        "beta": 0.194,
        "price": 1889.2,
        "lastAnnualDividend": 8,
        "volume": 271034,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ICICIBANK.BO",
        "companyName": "ICICI Bank Limited",
        "marketCap": 10019489177600,
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "beta": 0.541,
        "price": 1406.65,
        "lastAnnualDividend": 10,
        "volume": 593307,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "SBIN.BO",
        "companyName": "State Bank of India",
        "marketCap": 7113814602000,
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "beta": 0.48,
        "price": 797.1,
        "lastAnnualDividend": 13.7,
        "volume": 738676,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "INFY.BO",
        "companyName": "Infosys Limited",
        "marketCap": 5898465106740,
        "sector": "Technology",
        "industry": "Information Technology Services",
        "beta": 0.573,
        "price": 1420.2,
        "lastAnnualDividend": 63,
        "volume": 771330,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "BAJFINANCE.BO",
        "companyName": "Bajaj Finance Limited",
        "marketCap": 5671554217628,
        "sector": "Financial Services",
        "industry": "Financial - Credit Services",
        "beta": 0.717,
        "price": 9164.05,
        "lastAnnualDividend": 36,
        "volume": 36735,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "HINDUNILVR.BO",
        "companyName": "Hindustan Unilever Limited",
        "marketCap": 5579456980545,
        "sector": "Consumer Defensive",
        "industry": "Household & Personal Products",
        "beta": 0.335,
        "price": 2374.65,
        "lastAnnualDividend": 53,
        "volume": 47106,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ITC.BO",
        "companyName": "ITC Limited",
        "marketCap": 5346657770000,
        "sector": "Consumer Defensive",
        "industry": "Tobacco",
        "beta": 0.074,
        "price": 427.25,
        "lastAnnualDividend": 14,
        "volume": 516159,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "LICI.BO",
        "companyName": "Life Insurance Corporation of India",
        "marketCap": 5082451821480,
        "sector": "Financial Services",
        "industry": "Insurance - Life",
        "beta": 0.479,
        "price": 803.55,
        "lastAnnualDividend": 6,
        "volume": 50388,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "LT.BO",
        "companyName": "Larsen & Toubro Limited",
        "marketCap": 4464521870000,
        "sector": "Industrials",
        "industry": "Engineering & Construction",
        "beta": 0.458,
        "price": 3246.5,
        "lastAnnualDividend": 28,
        "volume": 100208,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "KOTAKBANK.BO",
        "companyName": "Kotak Mahindra Bank Limited",
        "marketCap": 4350231924000,
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "beta": 0.421,
        "price": 2188,
        "lastAnnualDividend": 2,
        "volume": 194588,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "SUNPHARMA.BO",
        "companyName": "Sun Pharmaceutical Industries Limited",
        "marketCap": 4201252940220,
        "sector": "Healthcare",
        "industry": "Drug Manufacturers - Specialty & Generic",
        "beta": 0.548,
        "price": 1751.05,
        "lastAnnualDividend": 15.5,
        "volume": 21749,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TATAMTRDVR.BO",
        "companyName": "Tata Motors Limited",
        "marketCap": 3977942834082,
        "sector": "Consumer Cyclical",
        "industry": "Auto - Manufacturers",
        "beta": 1.779,
        "price": 765.15,
        "lastAnnualDividend": 3.1,
        "volume": 509268,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": false
    },
    {
        "symbol": "HCLTECH.BO",
        "companyName": "HCL Technologies Limited",
        "marketCap": 3902393143500,
        "sector": "Technology",
        "industry": "Information Technology Services",
        "beta": 0.486,
        "price": 1438.05,
        "lastAnnualDividend": 54,
        "volume": 112914,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "AXISBANK.BO",
        "companyName": "Axis Bank Limited",
        "marketCap": 3687955029500,
        "sector": "Financial Services",
        "industry": "Banks - Regional",
        "beta": 0.584,
        "price": 1190.65,
        "lastAnnualDividend": 1,
        "volume": 284005,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "MARUTI.BO",
        "companyName": "Maruti Suzuki India Limited",
        "marketCap": 3675775117380,
        "sector": "Consumer Cyclical",
        "industry": "Auto - Manufacturers",
        "beta": 0.366,
        "price": 11691.3,
        "lastAnnualDividend": 125,
        "volume": 7187,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "NTPC.BO",
        "companyName": "NTPC Limited",
        "marketCap": 3530557547000,
        "sector": "Utilities",
        "industry": "Regulated Electric",
        "beta": 0.278,
        "price": 364.1,
        "lastAnnualDividend": 8.25,
        "volume": 571458,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ULTRACEMCO.BO",
        "companyName": "UltraTech Cement Limited",
        "marketCap": 3501544920833,
        "sector": "Basic Materials",
        "industry": "Construction Materials",
        "beta": 0.433,
        "price": 11903,
        "lastAnnualDividend": 70,
        "volume": 3786,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "BAJAJFINSV.BO",
        "companyName": "Bajaj Finserv Ltd.",
        "marketCap": 3244440439475,
        "sector": "Financial Services",
        "industry": "Financial - Conglomerates",
        "beta": 0.796,
        "price": 2033.75,
        "lastAnnualDividend": 1,
        "volume": 110780,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ONGC.BO",
        "companyName": "Oil and Natural Gas Corporation Limited",
        "marketCap": 3063926950450,
        "sector": "Energy",
        "industry": "Oil & Gas Integrated",
        "beta": 0.396,
        "price": 243.55,
        "lastAnnualDividend": 13.5,
        "volume": 292278,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TITAN.BO",
        "companyName": "Titan Company Limited",
        "marketCap": 2951844060700,
        "sector": "Consumer Cyclical",
        "industry": "Luxury Goods",
        "beta": 0.335,
        "price": 3324.95,
        "lastAnnualDividend": 11,
        "volume": 20597,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "POWERGRID.BO",
        "companyName": "Power Grid Corporation of India Limited",
        "marketCap": 2872025280000,
        "sector": "Utilities",
        "industry": "Regulated Electric",
        "beta": 0.297,
        "price": 308.8,
        "lastAnnualDividend": 10.5,
        "volume": 201591,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "DMART.BO",
        "companyName": "Avenue Supermarts Limited",
        "marketCap": 2835536946595,
        "sector": "Consumer Defensive",
        "industry": "Discount Stores",
        "beta": 0.353,
        "price": 4357.45,
        "lastAnnualDividend": 0,
        "volume": 501945,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "HAL.BO",
        "companyName": "Hindustan Aeronautics Limited",
        "marketCap": 2821294215000,
        "sector": "Industrials",
        "industry": "Aerospace & Defense",
        "beta": 0.679,
        "price": 4218.6,
        "lastAnnualDividend": 38,
        "volume": 46968,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ADANIENT.BO",
        "companyName": "Adani Enterprises Limited",
        "marketCap": 2790866883440,
        "sector": "Energy",
        "industry": "Coal",
        "beta": 0.664,
        "price": 2418.05,
        "lastAnnualDividend": 1.3,
        "volume": 36834,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ADANIPORTS.BO",
        "companyName": "Adani Ports and Special Economic Zone Limited",
        "marketCap": 2721559126100,
        "sector": "Industrials",
        "industry": "Marine Shipping",
        "beta": 0.402,
        "price": 1259.9,
        "lastAnnualDividend": 6,
        "volume": 156979,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "WIPRO.BO",
        "companyName": "Wipro Limited",
        "marketCap": 2478067461788,
        "sector": "Technology",
        "industry": "Information Technology Services",
        "beta": 0.658,
        "price": 236.9,
        "lastAnnualDividend": 3,
        "volume": 2665453,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "JSWSTEEL.BO",
        "companyName": "JSW Steel Limited",
        "marketCap": 2463061168080,
        "sector": "Basic Materials",
        "industry": "Steel",
        "beta": 0.804,
        "price": 1007.2,
        "lastAnnualDividend": 7.3,
        "volume": 32615,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "COALINDIA.BO",
        "companyName": "Coal India Limited",
        "marketCap": 2457387989375,
        "sector": "Energy",
        "industry": "Coal",
        "beta": 0.015,
        "price": 398.75,
        "lastAnnualDividend": 26.35,
        "volume": 467528,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ASIANPAINT.BO",
        "companyName": "Asian Paints Limited",
        "marketCap": 2368883340700,
        "sector": "Basic Materials",
        "industry": "Chemicals - Specialty",
        "beta": 0.389,
        "price": 2469.65,
        "lastAnnualDividend": 32.4,
        "volume": 44422,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "NESTLEIND.BO",
        "companyName": "Nestlé India Limited",
        "marketCap": 2329017890760,
        "sector": "Consumer Defensive",
        "industry": "Packaged Foods",
        "beta": 0.231,
        "price": 2415.6,
        "lastAnnualDividend": 32.5,
        "volume": 40400,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TATAMOTORS.BO",
        "companyName": "Tata Motors Limited",
        "marketCap": 2287859585000,
        "sector": "Consumer Cyclical",
        "industry": "Auto - Manufacturers",
        "beta": 1.253,
        "price": 621.5,
        "lastAnnualDividend": 6,
        "volume": 1170273,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "BAJAJ-AUTO.BO",
        "companyName": "Bajaj Auto Limited",
        "marketCap": 2239017622400,
        "sector": "Consumer Cyclical",
        "industry": "Auto - Manufacturers",
        "beta": 0.912,
        "price": 8017.75,
        "lastAnnualDividend": 80,
        "volume": 8346,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "BEL.BO",
        "companyName": "Bharat Electronics Limited",
        "marketCap": 2157116078000,
        "sector": "Industrials",
        "industry": "Aerospace & Defense",
        "beta": 0.376,
        "price": 295.1,
        "lastAnnualDividend": 2.3,
        "volume": 1282704,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ADANIPOWER.BO",
        "companyName": "Adani Power Limited",
        "marketCap": 2119773674400,
        "sector": "Utilities",
        "industry": "Independent Power Producers",
        "beta": 0.205,
        "price": 549.6,
        "lastAnnualDividend": 0,
        "volume": 490595,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "INDIGO.BO",
        "companyName": "InterGlobe Aviation Limited",
        "marketCap": 2074097332992,
        "sector": "Industrials",
        "industry": "Airlines, Airports & Air Services",
        "beta": 0.708,
        "price": 5367.2,
        "lastAnnualDividend": 0,
        "volume": 32423,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "ZOMATO.BO",
        "companyName": "Zomato Limited",
        "marketCap": 1952939541504,
        "sector": "Consumer Cyclical",
        "industry": "Specialty Retail",
        "beta": 0.252,
        "price": 215.25,
        "lastAnnualDividend": 0,
        "volume": 3903870,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": false
    },
    {
        "symbol": "IOC.BO",
        "companyName": "Indian Oil Corporation Limited",
        "marketCap": 1896482263400,
        "sector": "Energy",
        "industry": "Oil & Gas Refining & Marketing",
        "beta": 0.712,
        "price": 134.3,
        "lastAnnualDividend": 15,
        "volume": 1280489,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "VBL.BO",
        "companyName": "Varun Beverages Limited",
        "marketCap": 1883361008330,
        "sector": "Consumer Defensive",
        "industry": "Beverages - Non-Alcoholic",
        "beta": 0.361,
        "price": 556.9,
        "lastAnnualDividend": 1,
        "volume": 628065,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "GRASIM.BO",
        "companyName": "Grasim Industries Limited",
        "marketCap": 1878878779599,
        "sector": "Basic Materials",
        "industry": "Construction Materials",
        "beta": 0.272,
        "price": 2760.7,
        "lastAnnualDividend": 10,
        "volume": 23846,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "HINDZINC.BO",
        "companyName": "Hindustan Zinc Limited",
        "marketCap": 1858929094050,
        "sector": "Basic Materials",
        "industry": "Industrial Materials",
        "beta": 0.682,
        "price": 439.95,
        "lastAnnualDividend": 35,
        "volume": 89648,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TRENT.BO",
        "companyName": "Trent Limited",
        "marketCap": 1823846187903,
        "sector": "Consumer Cyclical",
        "industry": "Apparel - Retail",
        "beta": 0.229,
        "price": 5130.55,
        "lastAnnualDividend": 3.2,
        "volume": 77071,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "TATASTEEL.BO",
        "companyName": "Tata Steel Limited",
        "marketCap": 1712104070300,
        "sector": "Basic Materials",
        "industry": "Steel",
        "beta": 1.087,
        "price": 137.15,
        "lastAnnualDividend": 3.6,
        "volume": 1378982,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "IRFC.BO",
        "companyName": "Indian Railway Finance Corporation Limited",
        "marketCap": 1691718101700,
        "sector": "Financial Services",
        "industry": "Financial - Credit Services",
        "beta": 0.355,
        "price": 129.45,
        "lastAnnualDividend": 2.3,
        "volume": 878322,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "DLF.BO",
        "companyName": "DLF Limited",
        "marketCap": 1657963642700,
        "sector": "Real Estate",
        "industry": "Real Estate - Development",
        "beta": 0.341,
        "price": 669.8,
        "lastAnnualDividend": 5,
        "volume": 120045,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "SBILIFE.BO",
        "companyName": "SBI Life Insurance Company Limited",
        "marketCap": 1612535589410,
        "sector": "Financial Services",
        "industry": "Insurance - Life",
        "beta": 0.496,
        "price": 1609.1,
        "lastAnnualDividend": 2.7,
        "volume": 13226,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "JIOFIN.BO",
        "companyName": "Jio Financial Services Limited",
        "marketCap": 1565731747320,
        "sector": "Financial Services",
        "industry": "Asset Management",
        "beta": 1.325606,
        "price": 246.45,
        "lastAnnualDividend": 0,
        "volume": 1282472,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    },
    {
        "symbol": "VEDL.BO",
        "companyName": "Vedanta Limited",
        "marketCap": 1564155200000,
        "sector": "Basic Materials",
        "industry": "Industrial Materials",
        "beta": 1.101,
        "price": 400,
        "lastAnnualDividend": 53.5,
        "volume": 264792,
        "exchange": "Bombay Stock Exchange",
        "exchangeShortName": "BSE",
        "country": "IN",
        "isEtf": false,
        "isFund": false,
        "isActivelyTrading": true
    }
];
  filteredData: any[] =this.stockData;

  listOfSectors:any[]= [...new Set(this.stockData.map(stock => stock.sector))].filter(Boolean);

  selectedSector: string = '';
  searchText: string = '';
  sortKey: string = '';
  sortAsc: boolean = true;

  filterAndSort() {
    let data = this.stockData;
    console.log(data);

    if (this.selectedSector){
      data = data.filter((stock) => stock.sector === this.selectedSector);
      console.log(data);
      
    }
    if (this.searchText)
      data = data.filter((stock) =>
        stock.companyName.toLowerCase().includes(this.searchText.toLowerCase())
      );
    if (this.sortKey) {
      data.sort((a, b) => {
        let aVal = a[this.sortKey];
        let bVal = b[this.sortKey];
        return this.sortAsc
          ? aVal.localeCompare(bVal)
          : bVal.localeCompare(aVal);
      });
    }

    this.filteredData = data;
  }

  toggleAndSort(key: string) {
    if (this.sortKey === key) {
      this.sortAsc = !this.sortAsc;
    } else {
      this.sortKey = key;
      this.sortAsc = true;
    }
    this.filterAndSort();
  }

  constructor(private stockService: StockApiService, private router: Router) {}

  ngOnInit(): void {
    // this.stockService.getStocks().subscribe((data) => {
    //   this.stockData = data;
    //   console.log(this.stockData);
    // });
    console.log(this.listOfSectors);
  }

  goToStock(stock:any){
    this.router.navigate(['/stocks', stock.companyName.replace(/\s+/g, '-')], { state: { stock} });
  }
}
